# Generated by Django 4.1.7 on 2023-02-27 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_doctor_specialist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='user',
        ),
    ]
