# Generated by Django 4.1.7 on 2023-03-06 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='certificate_image',
            field=models.ImageField(blank=True, null=True, upload_to='Photos/%y/%m/%d'),
        ),
    ]
