# Generated by Django 4.1.7 on 2023-03-22 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_doctor_certificate_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='is_live',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
