# Generated by Django 4.1.7 on 2023-03-22 23:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_doctor_views_docviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docviews',
            name='view',
            field=models.IntegerField(max_length=1, validators=[django.core.validators.MaxValueValidator(1)]),
        ),
    ]
