# Generated by Django 4.1.7 on 2023-03-22 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_docviews_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='docviews',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='doc', to='users.doctor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='docviews',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
