# Generated by Django 4.1.7 on 2023-03-22 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_docviews_doctor_alter_docviews_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docviews',
            name='doctor',
        ),
    ]
