# Generated by Django 4.1.7 on 2023-03-23 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_docviews_doc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': 'Doctors'},
        ),
        migrations.AlterField(
            model_name='doctor',
            name='views',
            field=models.IntegerField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='docviews',
            unique_together={('user', 'doc')},
        ),
        migrations.AlterIndexTogether(
            name='docviews',
            index_together={('user', 'doc')},
        ),
    ]
