# Generated by Django 4.1.7 on 2023-03-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_doctor_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='avg_rating',
            field=models.IntegerField(blank=True, max_length=150, null=True),
        ),
    ]
