# Generated by Django 4.1.7 on 2023-03-23 13:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_doctor_avg_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='likes',
            field=models.ManyToManyField(related_name='like', to=settings.AUTH_USER_MODEL),
        ),
    ]
