# Generated by Django 4.1.7 on 2023-03-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_doctor_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='is_liked',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
