# Generated by Django 4.1.7 on 2023-03-23 13:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_doctor_is_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='like', to=settings.AUTH_USER_MODEL),
        ),
    ]
