# Generated by Django 4.1.7 on 2023-03-23 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_doctor_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='is_liked',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='likes',
        ),
        migrations.CreateModel(
            name='DoctorLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_liked', models.BooleanField(blank=True, default=False, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctorlike', to='users.doctor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userlike', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
