# Generated by Django 4.1.7 on 2023-03-25 14:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_doctorlike_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorlike',
            name='likes',
        ),
        migrations.AddField(
            model_name='doctor',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='doctorlikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
