# Generated by Django 4.1.7 on 2023-03-28 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_doctor_doctorimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='DoctorImage',
            new_name='doctorImage',
        ),
    ]
