# Generated by Django 4.1.7 on 2023-03-28 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_rename_doctorimage_doctor_doctorimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='doctorImage',
        ),
    ]
