# Generated by Django 4.1.7 on 2023-03-29 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_remove_doctor_doctorimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='listOfSpecialist',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
