# Generated by Django 4.1.7 on 2023-04-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_alter_doctor_specialist'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='Photos/%y/%m/%d'),
        ),
    ]
