# Generated by Django 4.1.7 on 2023-04-16 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_alter_doctor_price_alter_doctor_views_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='listOfSpecialist',
        ),
    ]
