# Generated by Django 4.1.7 on 2023-04-27 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_remove_doctor_listofspecialist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificateImage', models.ImageField(blank=True, null=True, upload_to='Photos/%y/%m/%d')),
            ],
        ),
    ]
