# Generated by Django 4.1.7 on 2023-04-27 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='certificateImage',
            field=models.FileField(blank=True, null=True, upload_to='Photos/%y/%m/%d'),
        ),
    ]
