# Generated by Django 4.1.7 on 2023-05-07 22:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='doctorlikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='views',
        ),
        migrations.DeleteModel(
            name='DocViews',
        ),
        migrations.AddField(
            model_name='doctor',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='doctorviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
