# Generated by Django 4.1.7 on 2023-05-18 11:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_remove_doctor_all_views_alter_doctor_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='view',
            field=models.ManyToManyField(related_name='view', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='DocViews',
        ),
    ]
