# Generated by Django 4.1.7 on 2023-05-18 23:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_remove_doctor_view_docviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docviews',
            name='view',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='doctorlikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
