# Generated by Django 4.1.7 on 2023-03-23 11:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_doctor_options_alter_doctor_views_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ratingsystem',
            unique_together={('user', 'doctor')},
        ),
        migrations.AlterIndexTogether(
            name='ratingsystem',
            index_together={('user', 'doctor')},
        ),
    ]
