# Generated by Django 4.1.7 on 2023-03-23 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_ratingsystem_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RatingSystem',
        ),
    ]
